-- Dimensions
DELETE FROM hypercube.DIM_PATIENT;
DELETE FROM hypercube.DIM_TEMPS;
DELETE FROM hypercube.DIM_DIAGNOSTIC;
DELETE FROM hypercube.DIM_PROFESSIONNEL;
DELETE FROM hypercube.DIM_ETABLISSEMENT;
DELETE FROM hypercube.DIM_MUTUELLE;
DELETE FROM hypercube.DIM_LOCALISATION;
